[pxccluster]
activeFailover = 1
failBack = false
checkTimeOut = 200
debug = 1
mainSegment = 0
# sslClient = "client-cert.pem"
# sslKey = "client-key.pem"
# sslCa = "ca.pem"
# sslCertificate_path = "/Users/marcotusa/work/temp/ssl_test"
hgW = 100
hgR = 101
configHgRange =8000
maintenanceHgRange =9000
#bckHgW = 8100
#bckHgR = 8101
singlePrimary = false
maxNumWriters = 2
writerIsAlsoReader = 1
retryUp = 0
retryDown = 2
clusterId = 10

[proxysql]
port = 6032
host = "127.0.0.1"
user = "admin"
password = "admin"
clustered = false
lockfilepath ="/tmp/"

[global]
debug = true
logLevel = "debug"
logTarget = "file" #stdout | file
logFile = "/tmp/pscheduler.log"
development = false
devInterval = 2000
performance = true
OS = "na"

